version: '3.3'
services:
    pt-gui:
        build:
          context: .
          # Comment this out and use the below when developing
          dockerfile: Dockerfile
          #dockerfile: dev.Dockerfile
        environment:
            - DISPLAY=$DISPLAY
        volumes:
            - '/tmp/.X11-unix:/tmp/.X11-unix:rw'
